# Generated by Django 5.0.6 on 2024-05-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0005_user_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
